"""empty message

Revision ID: 1dbf8484236b
Revises: ab6ca139c325
Create Date: 2019-06-10 14:41:05.051952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbf8484236b'
down_revision = 'ab6ca139c325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'SYS_MENU', 'SYS_MENU', ['PARENT_ID'], ['ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SYS_MENU', type_='foreignkey')
    # ### end Alembic commands ###
