"""empty message

Revision ID: 58c2274b68f7
Revises: 1dbf8484236b
Create Date: 2019-06-12 15:01:32.547997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c2274b68f7'
down_revision = '1dbf8484236b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYS_DICT',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('VALUE', sa.String(length=64), nullable=True, comment='数据值'),
    sa.Column('LABEL', sa.String(length=64), nullable=False, comment='标签名'),
    sa.Column('TYPE', sa.String(length=64), nullable=False, comment='类型'),
    sa.Column('DESCRIPTION', sa.String(length=225), nullable=True, comment='描述'),
    sa.Column('SORT', sa.Integer(), nullable=True, comment='排序'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('VALUE', 'TYPE', name='uix_SYS_DICT_VALUE_TYPE')
    )
    op.create_index(op.f('ix_SYS_DICT_TYPE'), 'SYS_DICT', ['TYPE'], unique=False)
    op.create_index(op.f('ix_SYS_DICT_VALUE'), 'SYS_DICT', ['VALUE'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SYS_DICT_VALUE'), table_name='SYS_DICT')
    op.drop_index(op.f('ix_SYS_DICT_TYPE'), table_name='SYS_DICT')
    op.drop_table('SYS_DICT')
    # ### end Alembic commands ###
