"""empty message

Revision ID: 6dc6bf0fcbba
Revises: 8517ff8bf752
Create Date: 2019-05-31 10:37:40.896313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc6bf0fcbba'
down_revision = '8517ff8bf752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUDIO_LEXER_NE',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('CODE', sa.String(length=64), nullable=False, comment='词性code'),
    sa.Column('TITLE', sa.String(length=60), nullable=False, comment='词性说明'),
    sa.Column('COLOR', sa.String(length=30), nullable=False, comment='词性颜色'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_AUDIO_LEXER_NE_CODE'), 'AUDIO_LEXER_NE', ['CODE'], unique=True)
    op.drop_table('AUDIO_LEXER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUDIO_LEXER',
    sa.Column('ID', sa.VARCHAR(length=64, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CODE', sa.VARCHAR(length=64, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TITLE', sa.VARCHAR(length=60, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('COLOR', sa.VARCHAR(length=30, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CREATE_BY', sa.VARCHAR(length=64, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UPDATE_BY', sa.VARCHAR(length=64, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CREATE_DATE', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('UPDATE_DATE', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('REMARKS', sa.VARCHAR(collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__AUDIO_LE__3214EC27A6485202')
    )
    op.drop_index(op.f('ix_AUDIO_LEXER_NE_CODE'), table_name='AUDIO_LEXER_NE')
    op.drop_table('AUDIO_LEXER_NE')
    # ### end Alembic commands ###
