"""empty message

Revision ID: 73af2d3d2ba6
Revises: d2a5e24eb684
Create Date: 2019-04-28 10:43:18.888349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73af2d3d2ba6'
down_revision = 'd2a5e24eb684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LOAN_IMG_DETAIL', 'OCR_INFO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LOAN_IMG_DETAIL', sa.Column('OCR_INFO', sa.VARCHAR(collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
