"""empty message

Revision ID: 83703f424f0f
Revises: 6dc6bf0fcbba
Create Date: 2019-06-06 11:34:01.354824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83703f424f0f'
down_revision = '6dc6bf0fcbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYS_MENU',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('PARENT_ID', sa.String(length=64), nullable=True, comment='父级菜单ID'),
    sa.Column('NAME', sa.String(length=30), nullable=False, comment='菜单名称'),
    sa.Column('ICON', sa.String(length=64), nullable=False, comment='菜单图标'),
    sa.Column('SORT', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('HREF', sa.Text(), nullable=True, comment='链接'),
    sa.Column('SPREAD', sa.Boolean(), nullable=False, comment='是否展开'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SYS_MENU_PARENT_ID'), 'SYS_MENU', ['PARENT_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SYS_MENU_PARENT_ID'), table_name='SYS_MENU')
    op.drop_table('SYS_MENU')
    # ### end Alembic commands ###
