"""empty message

Revision ID: 8517ff8bf752
Revises: 
Create Date: 2019-05-30 09:09:08.927551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8517ff8bf752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUDIO_LEXER',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('CODE', sa.String(length=64), nullable=False, comment='词性code'),
    sa.Column('TITLE', sa.String(length=60), nullable=False, comment='词性说明'),
    sa.Column('COLOR', sa.String(length=30), nullable=False, comment='词性颜色'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_AUDIO_LEXER_CODE'), 'AUDIO_LEXER', ['CODE'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_AUDIO_LEXER_CODE'), table_name='AUDIO_LEXER')
    op.drop_table('AUDIO_LEXER')
    # ### end Alembic commands ###
