"""empty message

Revision ID: 8a5630cf2d93
Revises: 
Create Date: 2019-05-23 15:38:33.983185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5630cf2d93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APP_SYS',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('CODE', sa.String(length=64), nullable=False, comment='系统代号'),
    sa.Column('DESC', sa.String(length=50), nullable=False, comment='代号描述'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_APP_SYS_CODE'), 'APP_SYS', ['CODE'], unique=True)
    op.create_table('IMG_DATA',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('APP_ID', sa.String(length=64), nullable=False, comment='应用ID'),
    sa.Column('APP_SYS_ID', sa.String(length=64), nullable=False),
    sa.Column('PAGE_NUM', sa.Integer(), nullable=False, comment='PDF总页码数'),
    sa.Column('SUCCESS_NUM', sa.Integer(), nullable=False, comment='图片分割成功数'),
    sa.Column('FAIL_NUM', sa.Integer(), nullable=False, comment='图片分割失败数'),
    sa.Column('IS_HANDLE', sa.Boolean(), nullable=False, comment='是否处理完'),
    sa.Column('PUSH_URL', sa.String(), nullable=True, comment='推送地址'),
    sa.Column('PUSH_TIMES', sa.Integer(), nullable=False, comment='推送次数'),
    sa.Column('IS_PUSH', sa.Boolean(), nullable=False, comment='是否成功推送'),
    sa.ForeignKeyConstraint(['APP_SYS_ID'], ['APP_SYS.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_IMG_DATA_APP_ID'), 'IMG_DATA', ['APP_ID'], unique=True)
    op.create_index(op.f('ix_IMG_DATA_APP_SYS_ID'), 'IMG_DATA', ['APP_SYS_ID'], unique=False)
    op.create_table('IMG_DETAIL',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('IMG_DATA_ID', sa.String(length=64), nullable=False),
    sa.Column('PARENT_FILE_ID', sa.String(length=64), nullable=False, comment='父级文件ID'),
    sa.Column('FILE_ID', sa.String(length=64), nullable=False, comment='图片ID'),
    sa.Column('IMG_TYPE_ID', sa.String(length=64), nullable=True),
    sa.Column('IS_HANDLE', sa.Boolean(), nullable=False, comment='是否分类处理'),
    sa.Column('ERR_CODE', sa.String(), nullable=True, comment='错误代号'),
    sa.Column('ERR_MSG', sa.String(length=100), nullable=True, comment='错误信息'),
    sa.ForeignKeyConstraint(['IMG_DATA_ID'], ['IMG_DATA.ID'], ),
    sa.ForeignKeyConstraint(['IMG_TYPE_ID'], ['IMG_TYPE.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_IMG_DETAIL_FILE_ID'), 'IMG_DETAIL', ['FILE_ID'], unique=True)
    op.create_index(op.f('ix_IMG_DETAIL_IMG_DATA_ID'), 'IMG_DETAIL', ['IMG_DATA_ID'], unique=False)
    op.create_index(op.f('ix_IMG_DETAIL_IMG_TYPE_ID'), 'IMG_DETAIL', ['IMG_TYPE_ID'], unique=False)
    op.create_index(op.f('ix_IMG_DETAIL_PARENT_FILE_ID'), 'IMG_DETAIL', ['PARENT_FILE_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_IMG_DETAIL_PARENT_FILE_ID'), table_name='IMG_DETAIL')
    op.drop_index(op.f('ix_IMG_DETAIL_IMG_TYPE_ID'), table_name='IMG_DETAIL')
    op.drop_index(op.f('ix_IMG_DETAIL_IMG_DATA_ID'), table_name='IMG_DETAIL')
    op.drop_index(op.f('ix_IMG_DETAIL_FILE_ID'), table_name='IMG_DETAIL')
    op.drop_table('IMG_DETAIL')
    op.drop_index(op.f('ix_IMG_DATA_APP_SYS_ID'), table_name='IMG_DATA')
    op.drop_index(op.f('ix_IMG_DATA_APP_ID'), table_name='IMG_DATA')
    op.drop_table('IMG_DATA')
    op.drop_index(op.f('ix_APP_SYS_CODE'), table_name='APP_SYS')
    op.drop_table('APP_SYS')
    # ### end Alembic commands ###
