"""empty message

Revision ID: a7e0676fc74f
Revises: 
Create Date: 2019-09-11 15:53:29.764057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e0676fc74f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OCR_FILE',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('APP_ID', sa.String(length=64), nullable=False, comment='应用ID'),
    sa.Column('APP_SYS_ID', sa.String(length=64), nullable=False),
    sa.Column('FILE_ID', sa.String(length=64), nullable=False, comment='文件ID'),
    sa.ForeignKeyConstraint(['APP_SYS_ID'], ['SYS_DICT.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('ix_OCR_FILE_APP_ID_APP_SYS_ID', 'OCR_FILE', ['APP_ID', 'APP_SYS_ID'], unique=True)
    op.create_index(op.f('ix_OCR_FILE_APP_SYS_ID'), 'OCR_FILE', ['APP_SYS_ID'], unique=False)
    op.create_index(op.f('ix_OCR_FILE_FILE_ID'), 'OCR_FILE', ['FILE_ID'], unique=True)
    op.create_table('MVSI_OCR',
    sa.Column('ID', sa.String(length=64), nullable=False, comment='主键ID'),
    sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('CREATE_DATE', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('UPDATE_DATE', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('REMARKS', sa.Text(), nullable=True, comment='备注'),
    sa.Column('OCR_FILE_ID', sa.String(length=64), nullable=False, comment='OCR流程ID'),
    sa.Column('CODE', sa.String(length=20), nullable=True, comment='发票代码'),
    sa.Column('NUMBER', sa.String(length=20), nullable=True, comment='发票号码'),
    sa.Column('ISSUE_DATE', sa.DateTime(), nullable=True, comment='开票日期'),
    sa.Column('MACHINE_PRINTED_CODE', sa.String(length=20), nullable=True, comment='机打代码'),
    sa.Column('MACHINE_PRINTED_NUMBER', sa.String(length=20), nullable=True, comment='机打号码'),
    sa.Column('MACHINE_NUMBER', sa.String(length=20), nullable=True, comment='机器编号'),
    sa.Column('FISCAL_CODE', sa.String(length=190), nullable=True, comment='税控码'),
    sa.Column('BUYER_NAME', sa.String(length=20), nullable=True, comment='购买方名称'),
    sa.Column('BUYER_ORGANIZATION_NAMBER', sa.String(length=30), nullable=True, comment='购买方身份证号码/组织机构代码'),
    sa.Column('BUYER_ID', sa.String(length=20), nullable=True, comment='购买方纳税人识别号'),
    sa.Column('SELLER_NAME', sa.Text(), nullable=True, comment='销售方名称'),
    sa.Column('SELLER_PHONE', sa.String(length=20), nullable=True, comment='销售方电话'),
    sa.Column('SELLER_ID', sa.String(length=20), nullable=True, comment='销售方纳税人识别号'),
    sa.Column('SELLER_ACCOUNT', sa.String(length=64), nullable=True, comment='销售方账号'),
    sa.Column('SELLER_ADDRESS', sa.Text(), nullable=True, comment='销售方地址'),
    sa.Column('SELLER_BANK', sa.Text(), nullable=True, comment='销售方开户行'),
    sa.Column('VEHICLE_TYPE', sa.Text(), nullable=True, comment='多用途乘用车'),
    sa.Column('BRAND_MODEL', sa.Text(), nullable=True, comment='厂牌型号'),
    sa.Column('MANUFACTURING_LOCATION', sa.String(length=225), nullable=True, comment='产地'),
    sa.Column('QUALITY_CERTIFICATE', sa.String(length=20), nullable=True, comment='合格证号'),
    sa.Column('IMPORT_CERTIFICATE', sa.String(length=18), nullable=True, comment='进口证明书号'),
    sa.Column('INSPECTION_NUMBER', sa.String(length=20), nullable=True, comment='商检单号'),
    sa.Column('ENGINE_NUMBER', sa.String(length=20), nullable=True, comment='发动机号码'),
    sa.Column('VEHICLE_IDENTIFICATION_NUMBER', sa.String(length=20), nullable=True, comment='车架号码'),
    sa.Column('TONNAGE', sa.String(length=10), nullable=True, comment='吨位'),
    sa.Column('SEATING_CAPACITY', sa.String(length=10), nullable=True, comment='限乘人数'),
    sa.Column('TAX_AUTHORITY', sa.Text(), nullable=True, comment='主管税务机关'),
    sa.Column('TAX_AUTHORITY_CODE', sa.String(length=20), nullable=True, comment='主管税务机关代码'),
    sa.Column('TAX_PAYMENT_RECEIPT', sa.String(length=18), nullable=True, comment='完税凭证号码'),
    sa.Column('TAX_RATE', sa.String(length=6), nullable=True, comment='增值税税率或征收率'),
    sa.Column('TAX', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False, comment='增值税税额'),
    sa.Column('TAX_EXCLUSIVE_PRICE', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False, comment='增值税税额'),
    sa.Column('TOTAL', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False, comment='价税合计'),
    sa.Column('TOTAL_CHINESE', sa.Text(), nullable=True, comment='价税合计大写'),
    sa.ForeignKeyConstraint(['OCR_FILE_ID'], ['OCR_FILE.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_MVSI_OCR_OCR_FILE_ID'), 'MVSI_OCR', ['OCR_FILE_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MVSI_OCR_OCR_FILE_ID'), table_name='MVSI_OCR')
    op.drop_table('MVSI_OCR')
    op.drop_index(op.f('ix_OCR_FILE_FILE_ID'), table_name='OCR_FILE')
    op.drop_index(op.f('ix_OCR_FILE_APP_SYS_ID'), table_name='OCR_FILE')
    op.drop_index('ix_OCR_FILE_APP_ID_APP_SYS_ID', table_name='OCR_FILE')
    op.drop_table('OCR_FILE')
    # ### end Alembic commands ###
