"""empty message

Revision ID: ab6ca139c325
Revises: f2c29d373e9b
Create Date: 2019-06-10 10:13:33.923987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6ca139c325'
down_revision = 'f2c29d373e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SYS_MENU', 'ICON',
               existing_type=sa.VARCHAR(length=64, collation='Chinese_PRC_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SYS_MENU', 'ICON',
               existing_type=sa.VARCHAR(length=64, collation='Chinese_PRC_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###
