"""empty message

Revision ID: d82df282f357
Revises: 
Create Date: 2019-05-02 15:30:43.937989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82df282f357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FILE', sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'))
    op.add_column('FILE', sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'))
    op.add_column('FLOW_TYPE', sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'))
    op.add_column('FLOW_TYPE', sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'))
    op.add_column('LOAN_FILE', sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'))
    op.add_column('LOAN_FILE', sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'))
    op.add_column('LOAN_IMG_DETAIL', sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'))
    op.add_column('LOAN_IMG_DETAIL', sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'))
    op.add_column('LOAN_IMG_TYPE', sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'))
    op.add_column('LOAN_IMG_TYPE', sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'))
    op.add_column('LOAN_TYPE', sa.Column('CREATE_BY', sa.String(length=64), nullable=True, comment='创建者'))
    op.add_column('LOAN_TYPE', sa.Column('UPDATE_BY', sa.String(length=64), nullable=True, comment='更新者'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LOAN_TYPE', 'UPDATE_BY')
    op.drop_column('LOAN_TYPE', 'CREATE_BY')
    op.drop_column('LOAN_IMG_TYPE', 'UPDATE_BY')
    op.drop_column('LOAN_IMG_TYPE', 'CREATE_BY')
    op.drop_column('LOAN_IMG_DETAIL', 'UPDATE_BY')
    op.drop_column('LOAN_IMG_DETAIL', 'CREATE_BY')
    op.drop_column('LOAN_FILE', 'UPDATE_BY')
    op.drop_column('LOAN_FILE', 'CREATE_BY')
    op.drop_column('FLOW_TYPE', 'UPDATE_BY')
    op.drop_column('FLOW_TYPE', 'CREATE_BY')
    op.drop_column('FILE', 'UPDATE_BY')
    op.drop_column('FILE', 'CREATE_BY')
    # ### end Alembic commands ###
